### PR TITLE
[UI] Resized feature section

### PR DESCRIPTION
**Pull request by chinel**

### CODE REVIEW

**Comment by adibas03** [comment]
@chinel You need to delete the `.vs` and `.idea` folders from the PR

**Comment by adibas03** [comment]
@chinel the folders are still in the PR.
You need to delete them and commit that

**Comment by adibas03** [comment]
The set width for the featured section is not responsive as it is, and once the screen width is greater than 992px, it becomes extremely obvious. We need the size to be smaller on larger screen sizes

**Comment by adibas03** [comment]
@chinel there is an overlapp at `width = 36px`

**Comment by chinel** [comment]
@adibas03 I don't understand

**Comment by adibas03** [comment]
@chinel Typo,
should be `376px`

**Pull request merged**
