### PR TITLE
[UI] Corrected Responsiveness issues/errors

### PR DESCRIPTION
**Pull request by chinel**

### CODE REVIEW

**Comment by adibas03** [comment]
@chinel Please attend to the failing ci
https://travis-ci.org/ico-busses/token-transfer-dapp/builds/500277311?utm_source=github_status&utm_medium=notification

**Comment by chinel** [comment]
errors corrected @adibas03

**Comment by adibas03** [comment]
@chinel You need to remove the `.vs` and `.idea` folders from the PR.

**Comment by adibas03** [comment]
the folders are still in the PR.
You need to delete them and commit that

**Pull request merged**
